development:
  adapter:  postgresql
  host:     localhost
  encoding: utf-8
  database: react-rails-redux-sample
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: utf-8
  database: react-rails-redux-sample
  pool:     5

production:
  adapter:  postgresql
  host:     localhost
  encoding: utf-8
  database: react-rails-redux-sample
  pool:     5
